# docker-compose.yml - Simplified without health checks
networks:
  ecostore-network:
    driver: bridge

volumes:
  mongo-user-data:
  mongo-product-data:
  mongo-cart-data:
  mongo-order-data:
  mongo-payment-data:
  mongo-admin-data:
  product-images:

services:
  # Databases
  mongo-user:
    image: mongo:6.0
    container_name: ecostore-mongo-user
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-user-data:/data/db
    networks:
      - ecostore-network

  mongo-product:
    image: mongo:6.0
    container_name: ecostore-mongo-product
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-product-data:/data/db
    networks:
      - ecostore-network

  mongo-cart:
    image: mongo:6.0
    container_name: ecostore-mongo-cart
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-cart-data:/data/db
    networks:
      - ecostore-network

  mongo-order:
    image: mongo:6.0
    container_name: ecostore-mongo-order
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-order-data:/data/db
    networks:
      - ecostore-network

  mongo-payment:
    image: mongo:6.0
    container_name: ecostore-mongo-payment
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-payment-data:/data/db
    networks:
      - ecostore-network

  mongo-admin:
    image: mongo:6.0
    container_name: ecostore-mongo-admin
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-admin-data:/data/db
    networks:
      - ecostore-network

  # Services (without health checks)
  user-service:
    image: minindu20021116/ecostore-user-service:latest
    container_name: ecostore-user-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://admin:password123@mongo-user:27017/user-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongo-user
    networks:
      - ecostore-network

  product-service:
    image: minindu20021116/ecostore-product-service:latest
    container_name: ecostore-product-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4001
      MONGO_URI: mongodb://admin:password123@mongo-product:27017/product-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
    volumes:
      - product-images:/app/public/product-images
    depends_on:
      - mongo-product
    networks:
      - ecostore-network

  cart-service:
    image: minindu20021116/ecostore-cart-service:latest
    container_name: ecostore-cart-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4002
      MONGO_URI: mongodb://admin:password123@mongo-cart:27017/cart-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
      PRODUCT_SERVICE_URL: http://product-service:4001
    depends_on:
      - mongo-cart
      - product-service
    networks:
      - ecostore-network

  order-service:
    image: minindu20021116/ecostore-order-service:latest
    container_name: ecostore-order-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4003
      MONGO_URI: mongodb://admin:password123@mongo-order:27017/order-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
      CART_SERVICE_URL: http://cart-service:4002
      PRODUCT_SERVICE_URL: http://product-service:4001
    depends_on:
      - mongo-order
      - cart-service
    networks:
      - ecostore-network

  payment-service:
    image: minindu20021116/ecostore-payment-service:latest
    container_name: ecostore-payment-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4004
      MONGO_URI: mongodb://admin:password123@mongo-payment:27017/payment-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
      ORDER_SERVICE_URL: http://order-service:4003
      PAYPAL_CLIENT_ID: AbKsB1xZlpjfyHvTsYZ2E8cqyeI4CqNgTOtfnPMLyyACFcF3FDNgQOb68AtL0C8hrAKJFQRGBGrKWjxm
      PAYPAL_CLIENT_SECRET: EG5M0mcfJ4d_LqmVXY5BhE8ZUGLUjNDvlzFRIZ-ZZ_7xr_RS3ki-LmrhY55rb3eAEMEE31Un0jrqGTLg
      PAYPAL_MODE: sandbox
    depends_on:
      - mongo-payment
      - order-service
    networks:
      - ecostore-network

  admin-service:
    image: minindu20021116/ecostore-admin-service:latest
    container_name: ecostore-admin-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4006
      MONGO_URI: mongodb://admin:password123@mongo-admin:27017/admin-service?authSource=admin
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      FRONTEND_URL: http://localhost:5173
      USER_SERVICE_URL: http://user-service:4000
      PRODUCT_SERVICE_URL: http://product-service:4001
      CART_SERVICE_URL: http://cart-service:4002
      ORDER_SERVICE_URL: http://order-service:4003
      PAYMENT_SERVICE_URL: http://payment-service:4004
    depends_on:
      - mongo-admin
    networks:
      - ecostore-network

  gateway:
    image: minindu20021116/ecostore-gateway:latest
    container_name: ecostore-gateway
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: YouAreMySunshineMyOnlySunshineYouMakeMeHappy
      USER_SERVICE_URL: http://user-service:4000
      PRODUCT_SERVICE_URL: http://product-service:4001
      CART_SERVICE_URL: http://cart-service:4002
      ORDER_SERVICE_URL: http://order-service:4003
      PAYMENT_SERVICE_URL: http://payment-service:4004
      ADMIN_SERVICE_URL: http://admin-service:4006
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service
      - admin-service
    networks:
      - ecostore-network