# docker-compose.dev.yml
# Development setup with hot reloading and debugging
version: '3.8'

networks:
  ecostore-dev:
    driver: bridge

services:
  # MongoDB for Order Service (Development)
  mongo-order-dev:
    image: mongo:6.0
    container_name: ecostore-mongo-order-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: order-service-dev
    ports:
      - "27018:27017"
    volumes:
      - mongo-order-dev-data:/data/db
      - ./init-mongo-order.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecostore-dev

  # MongoDB for Payment Service (Development)
  mongo-payment-dev:
    image: mongo:6.0
    container_name: ecostore-mongo-payment-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: payment-service-dev
    ports:
      - "27019:27017"
    volumes:
      - mongo-payment-dev-data:/data/db
      - ./init-mongo-payment.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecostore-dev

  # RabbitMQ (Development)
  rabbitmq-dev:
    image: rabbitmq:3.11-management-alpine
    container_name: ecostore-rabbitmq-dev
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: ecostore-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq
    networks:
      - ecostore-dev

  # Gateway Service (Development with hot reload)
  gateway-dev:
    build:
      context: ./backend/services/Gateway
      dockerfile: Dockerfile.dev
    container_name: ecostore-gateway-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: dev-secret-key-not-for-production
      DEBUG: ecostore:*
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    volumes:
      - ./backend/services/Gateway:/app
      - /app/node_modules
    networks:
      - ecostore-dev
    depends_on:
      - order-service-dev
      - payment-service-dev

  # Order Service (Development with hot reload)
  order-service-dev:
    build:
      context: ./backend/services/order-service
      dockerfile: Dockerfile.dev
    container_name: ecostore-order-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4003
      MONGO_URI: mongodb://admin:password123@mongo-order-dev:27017/order-service-dev?authSource=admin
      JWT_SECRET: dev-secret-key-not-for-production
      FRONTEND_URL: http://localhost:5173
      CART_SERVICE_URL: http://localhost:4002
      PRODUCT_SERVICE_URL: http://localhost:4001
      RABBITMQ_URL: amqp://admin:password123@rabbitmq-dev:5672/ecostore-dev
      RABBITMQ_EXCHANGE: ecostore.events.dev
      RABBITMQ_QUEUE_PREFIX: ecostore-dev
      ENABLE_RABBITMQ: "true"
      DEBUG: ecostore:order:*
    ports:
      - "4003:4003"
      - "9230:9229"  # Debug port
    volumes:
      - ./backend/services/order-service:/app
      - ./backend/shared:/app/shared
      - /app/node_modules
    networks:
      - ecostore-dev
    depends_on:
      - mongo-order-dev
      - rabbitmq-dev

  # Payment Service (Development with hot reload)
  payment-service-dev:
    build:
      context: ./backend/services/payment-service
      dockerfile: Dockerfile.dev
    container_name: ecostore-payment-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4004
      MONGO_URI: mongodb://admin:password123@mongo-payment-dev:27017/payment-service-dev?authSource=admin
      JWT_SECRET: dev-secret-key-not-for-production
      FRONTEND_URL: http://localhost:5173
      ORDER_SERVICE_URL: http://order-service-dev:4003
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID:-sandbox-paypal-client-id}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET:-sandbox-paypal-secret}
      PAYPAL_MODE: sandbox
      RABBITMQ_URL: amqp://admin:password123@rabbitmq-dev:5672/ecostore-dev
      RABBITMQ_EXCHANGE: ecostore.events.dev
      RABBITMQ_QUEUE_PREFIX: ecostore-dev
      ENABLE_RABBITMQ: "true"
      DEBUG: ecostore:payment:*
    ports:
      - "4004:4004"
      - "9231:9229"  # Debug port
    volumes:
      - ./backend/services/payment-service:/app
      - ./backend/shared:/app/shared
      - /app/node_modules
    networks:
      - ecostore-dev
    depends_on:
      - mongo-payment-dev
      - rabbitmq-dev
      - order-service-dev

  # Redis for caching (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: ecostore-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - ecostore-dev
    command: redis-server --appendonly yes

volumes:
  mongo-order-dev-data:
    driver: local
  mongo-payment-dev-data:
    driver: local
  rabbitmq-dev-data:
    driver: local
  redis-dev-data:
    driver: local